# Allows for the definition of PR /commands
name: 'ðŸ“Ÿ Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    # Only run on pull request comments, not issue comments
    if: github.event.issue.pull_request
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@master
    secrets:
      token: .
